In [132]:
import pandas as pd
import numpy as np

import datetime
import pickle

In [186]:
test =  pd.read_csv('./test2_05_2018/CD_ALL_2018-05-02.csv', sep='>', na_values='<null>', 
                     parse_dates=['LAST_CARD_STATUS_DT', 'LAST_CONTR_STATUS_DT'], encoding='latin-1')

C:\Users\Liksakov\AppData\Local\Continuum\anaconda3_2\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (1164,1171,1173,1177,1182,1183,1184,1185) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [187]:
test.head()

,CLIENT_ID,CONTRACT_REF,BANK,label,TOTAL_BAL_NEG_CHNG_MAX_180,TOTAL_BAL_NEG_CHNG_MAX_31,TOTAL_BAL_NEG_CHNG_MAX_7,TOTAL_BAL_NEG_CHNG_MAX_90,TOTAL_BAL_NEG_CHNG_MIN_180,TOTAL_BAL_NEG_CHNG_MIN_31,...,CL_CCY_DOP,CL_AMT_DOP,FL_DIR_UCH,FL_4P,FL_DOC_PROFIT,REP_POPULATION,FL_PENS_DOC,FL_FRNG_PASSP,FL_FRGN_TRIP,BIRTH_DT
0,101947485,271-P-00303161,BBKK,1,0.00,0.0,0.0,0.0,0.00,0.0,...,UAH,0,N,N,N,511000.0,N,N,N,1989-02-03
1,105173333,271-P-00687159,BBKK,1,-1.83,0.0,0.0,0.0,-1.83,0.0,...,N,406900,N,N,N,21326.0,NaN,NaN,NaN,NaN
2,101863520,271-P-00559853,BBKK,1,0.00,0.0,0.0,0.0,0.00,0.0,...,10000,N,N,N,191300,NaN,N,N,32399,NaN
3,101839082,271-P-02328844,BBKK,1,-150.00,-150.0,0.0,-150.0,-190000.00,-67719.0,...,N,0,N,N,N,28937.0,NaN,NaN,NaN,NaN
4,101737216,271-P-02926365,BBKK,1,-19870.00,0.0,0.0,-19870.0,-19870.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [195]:
train['BAL']

0             0.00
1             0.00
2           407.44
3            45.05
4        -27803.59
5        -15513.84
6             0.00
7          5334.07
8           176.58
9           181.99
10            0.00
11           13.07
12        -8458.01
13            0.00
14          557.17
15        -8341.50
16            0.00
17            0.05
18       -21768.61
19            0.00
20        -1012.15
21            0.00
22       -51092.10
23       -28557.05
24            0.00
25            0.00
26          952.15
27            0.00
28            0.00
29       -19766.21
            ...
114690        0.00
114691        0.00
114692        0.00
114693        0.00
114694        0.00
114695   -28611.69
114696       99.13
114697        0.00
114698       51.14
114699       74.19
114700        0.00
114701        0.00
114702        0.00
114703        0.00
114704        0.00
114705        0.00
114706        0.00
114707      603.46
114708   -52369.97
114709   -32156.70
114710        0.00
114711        0.00
114712       15.30
114713        0.00
114714   -29327.38
114715        0.00
114716      254.97
114717        0.00
114718      136.68
114719        0.00
Name: BAL, Length: 114720, dtype: float64

In [ ]:
test[]

In [206]:
print(train['CL_INDUSTR'].value_counts().head(10), "\n")
print(test['CL_ESTATE_TYPE'].value_counts().head(10))

TRADE              13678
ETC                11047
SERVICESECTOR       9106
EDUCATION           6195
HEALTH              4492
CONSTRUCTION        4405
TRANSPORTATION      3356
LIGHTINDUSTRIES     2876
CIVILSERVANTS       2154
ENGINEERING         1687
Name: CL_INDUSTR, dtype: int64

RUR                  19319
N                     6277
0                     6221
PERSONALPROPERTY      5386
JOINTLYPROPERTY       3659
LIVINGWITHPARENTS     1924
UAH                   1846
15000                 1013
10000                  977
20000                  877
Name: CL_ESTATE_TYPE, dtype: int64

In [194]:
train.columns.tolist()

['CONTRACT_REF',
 'CLIENT_ID',
 'CONTROL_GROUP_FLG',
 'START_DATE',
 'TARGET',
 '11_AddrCity2',
 '11_AddrCountry',
 '12_AddrCity2',
 '12_AddrCountry',
 '13_AddrCity2',
 '13_AddrCountry',
 'BAL',
 'BANK',
 'BIRTH_DATE',
 'CARD_CONTR_COUNT_0',
 'CARD_STATUS_14',
 'CARD_STATUS_176',
 'CL_AMT_DOP',
 'CL_AMT_ZP',
 'CL_AUTO_EX',
 'CL_CCY_DOP',
 'CL_CCY_ZP',
 'CL_EDU',
 'CL_ESTATE_TYPE',
 'CL_FAM_ST',
 'CL_INDUSTR',
 'CL_OFF_POS',
 'CL_OWN_TYPE',
 'CL_SOC_ST',
 'CODE_17_MAX_180',
 'CODE_17_MEAN_180',
 'CODE_17_N_180',
 'CODE_17_SUM_180',
 'CODE_26_MAX_180',
 'CODE_26_MEAN_180',
 'CODE_26_N_180',
 'CODE_26_SUM_180',
 'CODE_2_MAX_180',
 'CODE_2_MEAN_180',
 'CODE_2_N_180',
 'CODE_2_SUM_180',
 'CODE_35_MAX_180',
 'CODE_35_MEAN_180',
 'CODE_35_N_180',
 'CODE_35_SUM_180',
 'CODE_46_MAX_180',
 'CODE_46_MEAN_180',
 'CODE_46_N_180',
 'CODE_46_SUM_180',
 'CODE_59_MAX_180',
 'CODE_59_MEAN_180',
 'CODE_59_N_180',
 'CODE_59_SUM_180',
 'CODE_67_MAX_180',
 'CODE_67_MAX_90',
 'CODE_67_MEAN_180',
 'CODE_67_MEAN_90',
 'CODE_67_N_180',
 'CODE_67_N_90',
 'CODE_67_SUM_180',
 'CODE_67_SUM_90',
 'CODE_NA_MAX_180',
 'CODE_NA_MAX_90',
 'CODE_NA_MEAN_180',
 'CODE_NA_MEAN_90',
 'CODE_NA_N_180',
 'CODE_NA_N_90',
 'CODE_NA_SUM_180',
 'CODE_NA_SUM_90',
 'FL_4P',
 'FL_CR_PAN',
 'FL_DIR_UCH',
 'FL_DOC_PROFIT',
 'FL_FRGN_TRIP',
 'FL_FRNG_PASSP',
 'FL_GOLD',
 'FL_MOBB',
 'FL_P24',
 'FL_PENS',
 'FL_PENS_DOC',
 'FL_SMSI',
 'FL_SOC',
 'FL_STUD',
 'FL_ZP',
 'Home',
 'IS_LOYALTY_AUTO',
 'LAST_CARD_STATUS',
 'LAST_CARD_STATUS_DT',
 'LAST_CONTR_STATUS_DT',
 'LIM_AVG_CHANGE',
 'LIM_AVG_N_CHANGES',
 'LIM_AVG_N_POS_CHANGE',
 'LIM_AVG_POS_CHANGE',
 'LIM_MAX_POS_CHANGE',
 'LIM_MIN_POS_CHANGE',
 'LIM_RECENT',
 'MEAN_DAYS_DIFF_CHANGE_0',
 'MEAN_STATUS_COUNT_0',
 'Mobile',
 'QTY_CHLD',
 'REP_POPULATION',
 'REP_SEX',
 'SCENARIO_NAME_UNI',
 'TOTAL_BAL_NEG_CHNG_MAX_180',
 'TOTAL_BAL_NEG_CHNG_MAX_31',
 'TOTAL_BAL_NEG_CHNG_MAX_7',
 'TOTAL_BAL_NEG_CHNG_MAX_90',
 'TOTAL_BAL_NEG_CHNG_MIN_180',
 'TOTAL_BAL_NEG_CHNG_MIN_31',
 'TOTAL_BAL_NEG_CHNG_MIN_7',
 'TOTAL_BAL_NEG_CHNG_MIN_90',
 'TOTAL_BAL_NEG_CHNG_N_180',
 'TOTAL_BAL_NEG_CHNG_N_31',
 'TOTAL_BAL_NEG_CHNG_N_7',
 'TOTAL_BAL_NEG_CHNG_N_90',
 'TOTAL_BAL_NEG_CHNG_SUM_180',
 'TOTAL_BAL_NEG_CHNG_SUM_31',
 'TOTAL_BAL_NEG_CHNG_SUM_7',
 'TOTAL_BAL_NEG_CHNG_SUM_90',
 'TOTAL_BAL_POS_CHNG_MAX_180',
 'TOTAL_BAL_POS_CHNG_MAX_31',
 'TOTAL_BAL_POS_CHNG_MAX_7',
 'TOTAL_BAL_POS_CHNG_MAX_90',
 'TOTAL_BAL_POS_CHNG_MIN_180',
 'TOTAL_BAL_POS_CHNG_MIN_31',
 'TOTAL_BAL_POS_CHNG_MIN_7',
 'TOTAL_BAL_POS_CHNG_MIN_90',
 'TOTAL_BAL_POS_CHNG_N_180',
 'TOTAL_BAL_POS_CHNG_N_31',
 'TOTAL_BAL_POS_CHNG_N_7',
 'TOTAL_BAL_POS_CHNG_N_90',
 'TOTAL_BAL_POS_CHNG_SUM_180',
 'TOTAL_BAL_POS_CHNG_SUM_31',
 'TOTAL_BAL_POS_CHNG_SUM_7',
 'TOTAL_BAL_POS_CHNG_SUM_90',
 'TOTAL_DEBT_NEG_CHNG_MAX_180',
 'TOTAL_DEBT_NEG_CHNG_MIN_180',
 'TOTAL_DEBT_NEG_CHNG_N_180',
 'TOTAL_DEBT_NEG_CHNG_SUM_180',
 'TOTAL_DEBT_POS_CHNG_MAX_180',
 'TOTAL_DEBT_POS_CHNG_MIN_180',
 'TOTAL_DEBT_POS_CHNG_N_180',
 'TOTAL_DEBT_POS_CHNG_SUM_180',
 'TOTAL_MAX_180',
 'TOTAL_MAX_31',
 'TOTAL_MAX_90',
 'TOTAL_MEAN_180',
 'TOTAL_MEAN_31',
 'TOTAL_MEAN_90',
 'TOTAL_N_180',
 'TOTAL_N_31',
 'TOTAL_N_90',
 'TOTAL_SUM_180',
 'TOTAL_SUM_31',
 'TOTAL_SUM_90',
 'TXN_CHN_Internet purchase_MAX_180',
 'TXN_CHN_Internet purchase_MAX_90',
 'TXN_CHN_Internet purchase_MEAN_180',
 'TXN_CHN_Internet purchase_MEAN_90',
 'TXN_CHN_Internet purchase_N_180',
 'TXN_CHN_Internet purchase_N_90',
 'TXN_CHN_Internet purchase_SUM_180',
 'TXN_CHN_Internet purchase_SUM_90',
 'TXN_CHN_Our ATM_MAX_180',
 'TXN_CHN_Our ATM_MEAN_180',
 'TXN_CHN_Our ATM_N_180',
 'TXN_CHN_Our ATM_SUM_180',
 'TXN_CHN_POS terminal_MAX_180',
 'TXN_CHN_POS terminal_MAX_31',
 'TXN_CHN_POS terminal_MAX_90',
 'TXN_CHN_POS terminal_MEAN_180',
 'TXN_CHN_POS terminal_MEAN_31',
 'TXN_CHN_POS terminal_MEAN_90',
 'TXN_CHN_POS terminal_N_180',
 'TXN_CHN_POS terminal_N_31',
 'TXN_CHN_POS terminal_N_90',
 'TXN_CHN_POS terminal_SUM_180',
 'TXN_CHN_POS terminal_SUM_31',
 'TXN_CHN_POS terminal_SUM_90',
 'TXN_CHN_Unknown_MAX_180',
 'TXN_CHN_Unknown_MEAN_180',
 'TXN_CHN_Unknown_N_180',
 'TXN_CHN_Unknown_SUM_180',
 'TXN_TP_ATM_MAX_180',
 'TXN_TP_ATM_MEAN_180',
 'TXN_TP_ATM_N_180',
 'TXN_TP_ATM_SUM_180',
 'TXN_TP_Credit_MAX_180',
 'TXN_TP_Credit_MAX_90',
 'TXN_TP_Credit_MEAN_180',
 'TXN_TP_Credit_MEAN_90',
 'TXN_TP_Credit_N_180',
 'TXN_TP_Credit_N_90',
 'TXN_TP_Credit_SUM_180',
 'TXN_TP_Credit_SUM_90',
 'TXN_TP_MT_MAX_180',
 'TXN_TP_MT_MEAN_180',
 'TXN_TP_MT_N_180',
 'TXN_TP_MT_SUM_180',
 'TXN_TP_POS_MAX_180',
 'TXN_TP_POS_MAX_31',
 'TXN_TP_POS_MAX_90',
 'TXN_TP_POS_MEAN_180',
 'TXN_TP_POS_MEAN_31',
 'TXN_TP_POS_MEAN_90',
 'TXN_TP_POS_N_180',
 'TXN_TP_POS_N_31',
 'TXN_TP_POS_N_90',
 'TXN_TP_POS_SUM_180',
 'TXN_TP_POS_SUM_31',
 'TXN_TP_POS_SUM_90',
 'TXN_TP_Purposeful credit_MAX_180',
 'TXN_TP_Purposeful credit_MEAN_180',
 'TXN_TP_Purposeful credit_N_180',
 'TXN_TP_Purposeful credit_SUM_180']

In [189]:
train['QTY_CHLD']

0         2.0
1         1.0
2         0.0
3         0.0
4         1.0
5         2.0
6         2.0
7         0.0
8         0.0
9         0.0
10        1.0
11        1.0
12        2.0
13        2.0
14        1.0
15        0.0
16        NaN
17        NaN
18        1.0
19        NaN
20        0.0
21        1.0
22        0.0
23        0.0
24        1.0
25        0.0
26        0.0
27        NaN
28        NaN
29        0.0
         ...
114690    NaN
114691    NaN
114692    0.0
114693    2.0
114694    0.0
114695    1.0
114696    3.0
114697    2.0
114698    0.0
114699    0.0
114700    0.0
114701    1.0
114702    1.0
114703    1.0
114704    0.0
114705    1.0
114706    0.0
114707    NaN
114708    1.0
114709    2.0
114710    0.0
114711    NaN
114712    1.0
114713    0.0
114714    0.0
114715    1.0
114716    0.0
114717    1.0
114718    3.0
114719    0.0
Name: QTY_CHLD, Length: 114720, dtype: float64

In [188]:
test['QTY_CHLD']

0              0
1              0
2              1
3              3
4              N
5              0
6              N
7              0
8              1
9              1
10             0
11             2
12             1
13             0
14           NaN
15             2
16       MARRIED
17             0
18             N
19             0
20           NaN
21             1
22           NaN
23             0
24             1
25       MARRIED
26             0
27             1
28             1
29             2
          ...
79514        NaN
79515        NaN
79516        NaN
79517        NaN
79518        NaN
79519        NaN
79520        NaN
79521        NaN
79522        NaN
79523        NaN
79524        NaN
79525        NaN
79526        NaN
79527        NaN
79528        NaN
79529        NaN
79530        NaN
79531        NaN
79532        NaN
79533        NaN
79534        NaN
79535        NaN
79536        NaN
79537        NaN
79538        NaN
79539        NaN
79540        NaN
79541        NaN
79542        NaN
79543        NaN
Name: QTY_CHLD, Length: 79544, dtype: object

In [172]:
#test = pd.read_csv('./test_05_2018/CD_ALL_2018-04-27.csv', 
#    na_values='<null>', sep='>', encoding='cp1251', 
#    parse_dates=['LAST_CARD_STATUS_DT', 'LAST_CONTR_STATUS_DT'])

In [173]:
#test.head()
test.shape

(79544, 1186)

In [174]:
#test.columns.tolist()

In [175]:
test = test[test['CONTRACT_REF'].isin(test['CONTRACT_REF'].drop_duplicates(keep=False))]
test['START_DATE'] = datetime.date(2018, 4, 26)
test.rename(columns={'BIRTH_DT':'BIRTH_DATE'}, inplace=True)

In [176]:
test.shape

(79544, 1187)

In [177]:
train = pd.read_csv('./train_data/train_dataset.csv', 
    na_values='<null>', sep='>', 
    parse_dates=['START_DATE', 'LAST_CARD_STATUS_DT', 'LAST_CONTR_STATUS_DT'])

In [178]:
losted_cols = train.columns\
    .difference(test.columns)\
    .difference(['CONTROL_GROUP_FLG', 'SCENARIO_NAME_UNI', 'START_DATE', 'TARGET']).tolist()
losted_cols

['11_AddrCity2',
 '11_AddrCountry',
 '12_AddrCity2',
 '12_AddrCountry',
 '13_AddrCity2',
 '13_AddrCountry']

In [43]:
#train.columns.tolist()

In [42]:
#test['CODE_17_MAX_180'].sort_values(ascending=False)

In [106]:
#train.columns.tolist()

In [141]:
#new_cols = test.columns\
#    .difference(train.columns)\
#    .difference(['CONTROL_GROUP_FLG', 'SCENARIO_NAME_UNI', 'START_DATE', 'TARGET']).tolist()
#new_cols

In [179]:
losted_cols

['11_AddrCity2',
 '11_AddrCountry',
 '12_AddrCity2',
 '12_AddrCountry',
 '13_AddrCity2',
 '13_AddrCountry']

In [181]:
# SAVE losted cols list so as not to use them in train !
print(len(losted_cols))
with open("./test_data/test_data_05_2018/test_lost_cols_list.bin", "wb") as fp:
    pickle.dump(losted_cols, fp)

6

Среди нехватающих фичей только транзакционные - заполним их нулями. + 'FL_FRGN_TRIP' + 'Addr'

In [182]:
losted_test = pd.DataFrame(
    data=np.zeros((test.shape[0], len(losted_cols))),
    index=test.index,
    columns=losted_cols
)

print(losted_test.shape)
losted_test.head()

(79544, 6)

,11_AddrCity2,11_AddrCountry,12_AddrCity2,12_AddrCountry,13_AddrCity2,13_AddrCountry
0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0

In [185]:
test["QTY_CHLD"]

0              0
1              0
2              1
3              3
4              N
5              0
6              N
7              0
8              1
9              1
10             0
11             2
12             1
13             0
14           NaN
15             2
16       MARRIED
17             0
18             N
19             0
20           NaN
21             1
22           NaN
23             0
24             1
25       MARRIED
26             0
27             1
28             1
29             2
          ...
79514        NaN
79515        NaN
79516        NaN
79517        NaN
79518        NaN
79519        NaN
79520        NaN
79521        NaN
79522        NaN
79523        NaN
79524        NaN
79525        NaN
79526        NaN
79527        NaN
79528        NaN
79529        NaN
79530        NaN
79531        NaN
79532        NaN
79533        NaN
79534        NaN
79535        NaN
79536        NaN
79537        NaN
79538        NaN
79539        NaN
79540        NaN
79541        NaN
79542        NaN
79543        NaN
Name: QTY_CHLD, Length: 79544, dtype: object

In [184]:
test.columns

Index(['CLIENT_ID', 'CONTRACT_REF', 'BANK', 'label',
       'TOTAL_BAL_NEG_CHNG_MAX_180', 'TOTAL_BAL_NEG_CHNG_MAX_31',
       'TOTAL_BAL_NEG_CHNG_MAX_7', 'TOTAL_BAL_NEG_CHNG_MAX_90',
       'TOTAL_BAL_NEG_CHNG_MIN_180', 'TOTAL_BAL_NEG_CHNG_MIN_31',
       ...
       'CL_AMT_DOP', 'FL_DIR_UCH', 'FL_4P', 'FL_DOC_PROFIT', 'REP_POPULATION',
       'FL_PENS_DOC', 'FL_FRNG_PASSP', 'FL_FRGN_TRIP', 'BIRTH_DATE',
       'START_DATE'],
      dtype='object', length=1187)

In [149]:
test.columns.tolist()

['CLIENT_ID',
 'CONTRACT_REF',
 'BANK',
 'label',
 'TOTAL_BAL_NEG_CHNG_MAX_180',
 'TOTAL_BAL_NEG_CHNG_MAX_31',
 'TOTAL_BAL_NEG_CHNG_MAX_7',
 'TOTAL_BAL_NEG_CHNG_MAX_90',
 'TOTAL_BAL_NEG_CHNG_MIN_180',
 'TOTAL_BAL_NEG_CHNG_MIN_31',
 'TOTAL_BAL_NEG_CHNG_MIN_7',
 'TOTAL_BAL_NEG_CHNG_MIN_90',
 'TOTAL_BAL_NEG_CHNG_N_180',
 'TOTAL_BAL_NEG_CHNG_N_31',
 'TOTAL_BAL_NEG_CHNG_N_7',
 'TOTAL_BAL_NEG_CHNG_N_90',
 'TOTAL_BAL_NEG_CHNG_SUM_180',
 'TOTAL_BAL_NEG_CHNG_SUM_31',
 'TOTAL_BAL_NEG_CHNG_SUM_7',
 'TOTAL_BAL_NEG_CHNG_SUM_90',
 'TOTAL_BAL_POS_CHNG_MAX_180',
 'TOTAL_BAL_POS_CHNG_MAX_31',
 'TOTAL_BAL_POS_CHNG_MAX_7',
 'TOTAL_BAL_POS_CHNG_MAX_90',
 'TOTAL_BAL_POS_CHNG_MIN_180',
 'TOTAL_BAL_POS_CHNG_MIN_31',
 'TOTAL_BAL_POS_CHNG_MIN_7',
 'TOTAL_BAL_POS_CHNG_MIN_90',
 'TOTAL_BAL_POS_CHNG_N_180',
 'TOTAL_BAL_POS_CHNG_N_31',
 'TOTAL_BAL_POS_CHNG_N_7',
 'TOTAL_BAL_POS_CHNG_N_90',
 'TOTAL_BAL_POS_CHNG_SUM_180',
 'TOTAL_BAL_POS_CHNG_SUM_31',
 'TOTAL_BAL_POS_CHNG_SUM_7',
 'TOTAL_BAL_POS_CHNG_SUM_90',
 'TOTAL_DEBT_NEG_CHNG_MAX_180',
 'TOTAL_DEBT_NEG_CHNG_MAX_31',
 'TOTAL_DEBT_NEG_CHNG_MAX_7',
 'TOTAL_DEBT_NEG_CHNG_MAX_90',
 'TOTAL_DEBT_NEG_CHNG_MIN_180',
 'TOTAL_DEBT_NEG_CHNG_MIN_31',
 'TOTAL_DEBT_NEG_CHNG_MIN_7',
 'TOTAL_DEBT_NEG_CHNG_MIN_90',
 'TOTAL_DEBT_NEG_CHNG_N_180',
 'TOTAL_DEBT_NEG_CHNG_N_31',
 'TOTAL_DEBT_NEG_CHNG_N_7',
 'TOTAL_DEBT_NEG_CHNG_N_90',
 'TOTAL_DEBT_NEG_CHNG_SUM_180',
 'TOTAL_DEBT_NEG_CHNG_SUM_31',
 'TOTAL_DEBT_NEG_CHNG_SUM_7',
 'TOTAL_DEBT_NEG_CHNG_SUM_90',
 'TOTAL_DEBT_POS_CHNG_MAX_180',
 'TOTAL_DEBT_POS_CHNG_MAX_31',
 'TOTAL_DEBT_POS_CHNG_MAX_90',
 'TOTAL_DEBT_POS_CHNG_MIN_180',
 'TOTAL_DEBT_POS_CHNG_MIN_31',
 'TOTAL_DEBT_POS_CHNG_MIN_90',
 'TOTAL_DEBT_POS_CHNG_N_180',
 'TOTAL_DEBT_POS_CHNG_N_31',
 'TOTAL_DEBT_POS_CHNG_N_90',
 'TOTAL_DEBT_POS_CHNG_SUM_180',
 'TOTAL_DEBT_POS_CHNG_SUM_31',
 'TOTAL_DEBT_POS_CHNG_SUM_90',
 'BAL',
 'IS_LOYALTY_AUTO',
 'IS_LOYALTY_BEAUTY',
 'IS_LOYALTY_ONLINE',
 'IS_LOYALTY_TRAVEL',
 'IS_LOYALTY_WEEKEND',
 'LIM_AVG_N_CHANGES',
 'LIM_MAX_POS_CHANGE',
 'LIM_MIN_POS_CHANGE',
 'LIM_MAX_NEG_CHANGE',
 'LIM_MIN_NEG_CHANGE',
 'LIM_AVG_CHANGE',
 'LIM_AVG_POS_CHANGE',
 'LIM_AVG_NEG_CHANGE',
 'LIM_AVG_N_POS_CHANGE',
 'LIM_AVG_N_NEG_CHANGE',
 'LIM_RECENT',
 'CARD_CONTR_COUNT_0',
 'MEAN_DAYS_DIFF_CHANGE_0',
 'MEAN_DAYS_DIFF_CHANGE_1',
 'MEAN_STATUS_COUNT_0',
 'MEAN_STATUS_COUNT_1',
 'LAST_CARD_STATUS_DT',
 'LAST_CARD_STATUS',
 'LAST_CONTR_STATUS_DT',
 'CARD_STATUS_-1',
 'CARD_STATUS_100000022',
 'CARD_STATUS_100000087',
 'CARD_STATUS_100000094',
 'CARD_STATUS_100000100',
 'CARD_STATUS_100000106',
 'CARD_STATUS_100000128',
 'CARD_STATUS_100000147',
 'CARD_STATUS_100000372',
 'CARD_STATUS_100000496',
 'CARD_STATUS_100000576',
 'CARD_STATUS_14',
 'CARD_STATUS_176',
 'CARD_STATUS_182',
 'CARD_STATUS_63',
 'CARD_STATUS_74',
 'CARD_STATUS_98',
 'CONTR_STATUS_100000021',
 'CONTR_STATUS_100000023',
 'CONTR_STATUS_100000024',
 'CONTR_STATUS_100000169',
 'CONTR_STATUS_100000534',
 'CONTR_STATUS_86',
 'Home',
 'Mobile',
 'CODE_1_MAX_180',
 'CODE_1_MAX_31',
 'CODE_1_MAX_90',
 'CODE_1_MEAN_180',
 'CODE_1_MEAN_31',
 'CODE_1_MEAN_90',
 'CODE_1_N_180',
 'CODE_1_N_31',
 'CODE_1_N_90',
 'CODE_1_SUM_180',
 'CODE_1_SUM_31',
 'CODE_1_SUM_90',
 'CODE_10_MAX_180',
 'CODE_10_MAX_31',
 'CODE_10_MAX_90',
 'CODE_10_MEAN_180',
 'CODE_10_MEAN_31',
 'CODE_10_MEAN_90',
 'CODE_10_N_180',
 'CODE_10_N_31',
 'CODE_10_N_90',
 'CODE_10_SUM_180',
 'CODE_10_SUM_31',
 'CODE_10_SUM_90',
 'CODE_11_MAX_180',
 'CODE_11_MAX_31',
 'CODE_11_MAX_90',
 'CODE_11_MEAN_180',
 'CODE_11_MEAN_31',
 'CODE_11_MEAN_90',
 'CODE_11_N_180',
 'CODE_11_N_31',
 'CODE_11_N_90',
 'CODE_11_SUM_180',
 'CODE_11_SUM_31',
 'CODE_11_SUM_90',
 'CODE_12_MAX_180',
 'CODE_12_MAX_31',
 'CODE_12_MAX_90',
 'CODE_12_MEAN_180',
 'CODE_12_MEAN_31',
 'CODE_12_MEAN_90',
 'CODE_12_N_180',
 'CODE_12_N_31',
 'CODE_12_N_90',
 'CODE_12_SUM_180',
 'CODE_12_SUM_31',
 'CODE_12_SUM_90',
 'CODE_13_MAX_180',
 'CODE_13_MAX_31',
 'CODE_13_MAX_90',
 'CODE_13_MEAN_180',
 'CODE_13_MEAN_31',
 'CODE_13_MEAN_90',
 'CODE_13_N_180',
 'CODE_13_N_31',
 'CODE_13_N_90',
 'CODE_13_SUM_180',
 'CODE_13_SUM_31',
 'CODE_13_SUM_90',
 'CODE_14_MAX_180',
 'CODE_14_MEAN_180',
 'CODE_14_N_180',
 'CODE_14_SUM_180',
 'CODE_15_MAX_180',
 'CODE_15_MAX_31',
 'CODE_15_MAX_7',
 'CODE_15_MAX_90',
 'CODE_15_MEAN_180',
 'CODE_15_MEAN_31',
 'CODE_15_MEAN_7',
 'CODE_15_MEAN_90',
 'CODE_15_N_180',
 'CODE_15_N_31',
 'CODE_15_N_7',
 'CODE_15_N_90',
 'CODE_15_SUM_180',
 'CODE_15_SUM_31',
 'CODE_15_SUM_7',
 'CODE_15_SUM_90',
 'CODE_16_MAX_180',
 'CODE_16_MAX_31',
 'CODE_16_MAX_90',
 'CODE_16_MEAN_180',
 'CODE_16_MEAN_31',
 'CODE_16_MEAN_90',
 'CODE_16_N_180',
 'CODE_16_N_31',
 'CODE_16_N_90',
 'CODE_16_SUM_180',
 'CODE_16_SUM_31',
 'CODE_16_SUM_90',
 'CODE_17_MAX_180',
 'CODE_17_MAX_31',
 'CODE_17_MAX_90',
 'CODE_17_MEAN_180',
 'CODE_17_MEAN_31',
 'CODE_17_MEAN_90',
 'CODE_17_N_180',
 'CODE_17_N_31',
 'CODE_17_N_90',
 'CODE_17_SUM_180',
 'CODE_17_SUM_31',
 'CODE_17_SUM_90',
 'CODE_18_MAX_180',
 'CODE_18_MAX_31',
 'CODE_18_MAX_90',
 'CODE_18_MEAN_180',
 'CODE_18_MEAN_31',
 'CODE_18_MEAN_90',
 'CODE_18_N_180',
 'CODE_18_N_31',
 'CODE_18_N_90',
 'CODE_18_SUM_180',
 'CODE_18_SUM_31',
 'CODE_18_SUM_90',
 'CODE_19_MAX_180',
 'CODE_19_MAX_31',
 'CODE_19_MAX_90',
 'CODE_19_MEAN_180',
 'CODE_19_MEAN_31',
 'CODE_19_MEAN_90',
 'CODE_19_N_180',
 'CODE_19_N_31',
 'CODE_19_N_90',
 'CODE_19_SUM_180',
 'CODE_19_SUM_31',
 'CODE_19_SUM_90',
 'CODE_2_MAX_180',
 'CODE_2_MAX_31',
 'CODE_2_MAX_90',
 'CODE_2_MEAN_180',
 'CODE_2_MEAN_31',
 'CODE_2_MEAN_90',
 'CODE_2_N_180',
 'CODE_2_N_31',
 'CODE_2_N_90',
 'CODE_2_SUM_180',
 'CODE_2_SUM_31',
 'CODE_2_SUM_90',
 'CODE_20_MAX_180',
 'CODE_20_MAX_31',
 'CODE_20_MAX_90',
 'CODE_20_MEAN_180',
 'CODE_20_MEAN_31',
 'CODE_20_MEAN_90',
 'CODE_20_N_180',
 'CODE_20_N_31',
 'CODE_20_N_90',
 'CODE_20_SUM_180',
 'CODE_20_SUM_31',
 'CODE_20_SUM_90',
 'CODE_21_MAX_180',
 'CODE_21_MAX_31',
 'CODE_21_MAX_90',
 'CODE_21_MEAN_180',
 'CODE_21_MEAN_31',
 'CODE_21_MEAN_90',
 'CODE_21_N_180',
 'CODE_21_N_31',
 'CODE_21_N_90',
 'CODE_21_SUM_180',
 'CODE_21_SUM_31',
 'CODE_21_SUM_90',
 'CODE_22_MAX_180',
 'CODE_22_MAX_90',
 'CODE_22_MEAN_180',
 'CODE_22_MEAN_90',
 'CODE_22_N_180',
 'CODE_22_N_90',
 'CODE_22_SUM_180',
 'CODE_22_SUM_90',
 'CODE_23_MAX_180',
 'CODE_23_MAX_31',
 'CODE_23_MAX_90',
 'CODE_23_MEAN_180',
 'CODE_23_MEAN_31',
 'CODE_23_MEAN_90',
 'CODE_23_N_180',
 'CODE_23_N_31',
 'CODE_23_N_90',
 'CODE_23_SUM_180',
 'CODE_23_SUM_31',
 'CODE_23_SUM_90',
 'CODE_24_MAX_180',
 'CODE_24_MAX_31',
 'CODE_24_MAX_90',
 'CODE_24_MEAN_180',
 'CODE_24_MEAN_31',
 'CODE_24_MEAN_90',
 'CODE_24_N_180',
 'CODE_24_N_31',
 'CODE_24_N_90',
 'CODE_24_SUM_180',
 'CODE_24_SUM_31',
 'CODE_24_SUM_90',
 'CODE_25_MAX_180',
 'CODE_25_MAX_31',
 'CODE_25_MAX_90',
 'CODE_25_MEAN_180',
 'CODE_25_MEAN_31',
 'CODE_25_MEAN_90',
 'CODE_25_N_180',
 'CODE_25_N_31',
 'CODE_25_N_90',
 'CODE_25_SUM_180',
 'CODE_25_SUM_31',
 'CODE_25_SUM_90',
 'CODE_26_MAX_180',
 'CODE_26_MAX_31',
 'CODE_26_MAX_90',
 'CODE_26_MEAN_180',
 'CODE_26_MEAN_31',
 'CODE_26_MEAN_90',
 'CODE_26_N_180',
 'CODE_26_N_31',
 'CODE_26_N_90',
 'CODE_26_SUM_180',
 'CODE_26_SUM_31',
 'CODE_26_SUM_90',
 'CODE_27_MAX_180',
 'CODE_27_MEAN_180',
 'CODE_27_N_180',
 'CODE_27_SUM_180',
 'CODE_28_MAX_180',
 'CODE_28_MAX_31',
 'CODE_28_MAX_90',
 'CODE_28_MEAN_180',
 'CODE_28_MEAN_31',
 'CODE_28_MEAN_90',
 'CODE_28_N_180',
 'CODE_28_N_31',
 'CODE_28_N_90',
 'CODE_28_SUM_180',
 'CODE_28_SUM_31',
 'CODE_28_SUM_90',
 'CODE_29_MAX_180',
 'CODE_29_MAX_90',
 'CODE_29_MEAN_180',
 'CODE_29_MEAN_90',
 'CODE_29_N_180',
 'CODE_29_N_90',
 'CODE_29_SUM_180',
 'CODE_29_SUM_90',
 'CODE_3_MAX_180',
 'CODE_3_MAX_31',
 'CODE_3_MAX_90',
 'CODE_3_MEAN_180',
 'CODE_3_MEAN_31',
 'CODE_3_MEAN_90',
 'CODE_3_N_180',
 'CODE_3_N_31',
 'CODE_3_N_90',
 'CODE_3_SUM_180',
 'CODE_3_SUM_31',
 'CODE_3_SUM_90',
 'CODE_30_MAX_180',
 'CODE_30_MAX_31',
 'CODE_30_MAX_90',
 'CODE_30_MEAN_180',
 'CODE_30_MEAN_31',
 'CODE_30_MEAN_90',
 'CODE_30_N_180',
 'CODE_30_N_31',
 'CODE_30_N_90',
 'CODE_30_SUM_180',
 'CODE_30_SUM_31',
 'CODE_30_SUM_90',
 'CODE_31_MAX_180',
 'CODE_31_MAX_31',
 'CODE_31_MAX_90',
 'CODE_31_MEAN_180',
 'CODE_31_MEAN_31',
 'CODE_31_MEAN_90',
 'CODE_31_N_180',
 'CODE_31_N_31',
 'CODE_31_N_90',
 'CODE_31_SUM_180',
 'CODE_31_SUM_31',
 'CODE_31_SUM_90',
 'CODE_32_MAX_180',
 'CODE_32_MAX_31',
 'CODE_32_MAX_90',
 'CODE_32_MEAN_180',
 'CODE_32_MEAN_31',
 'CODE_32_MEAN_90',
 'CODE_32_N_180',
 'CODE_32_N_31',
 'CODE_32_N_90',
 'CODE_32_SUM_180',
 'CODE_32_SUM_31',
 'CODE_32_SUM_90',
 'CODE_33_MAX_180',
 'CODE_33_MAX_31',
 'CODE_33_MAX_90',
 'CODE_33_MEAN_180',
 'CODE_33_MEAN_31',
 'CODE_33_MEAN_90',
 'CODE_33_N_180',
 'CODE_33_N_31',
 'CODE_33_N_90',
 'CODE_33_SUM_180',
 'CODE_33_SUM_31',
 'CODE_33_SUM_90',
 'CODE_34_MAX_180',
 'CODE_34_MAX_31',
 'CODE_34_MAX_90',
 'CODE_34_MEAN_180',
 'CODE_34_MEAN_31',
 'CODE_34_MEAN_90',
 'CODE_34_N_180',
 'CODE_34_N_31',
 'CODE_34_N_90',
 'CODE_34_SUM_180',
 'CODE_34_SUM_31',
 'CODE_34_SUM_90',
 'CODE_35_MAX_180',
 'CODE_35_MAX_31',
 'CODE_35_MAX_90',
 'CODE_35_MEAN_180',
 'CODE_35_MEAN_31',
 'CODE_35_MEAN_90',
 'CODE_35_N_180',
 'CODE_35_N_31',
 'CODE_35_N_90',
 'CODE_35_SUM_180',
 'CODE_35_SUM_31',
 'CODE_35_SUM_90',
 'CODE_36_MAX_180',
 'CODE_36_MAX_31',
 'CODE_36_MAX_90',
 'CODE_36_MEAN_180',
 'CODE_36_MEAN_31',
 'CODE_36_MEAN_90',
 'CODE_36_N_180',
 'CODE_36_N_31',
 'CODE_36_N_90',
 'CODE_36_SUM_180',
 'CODE_36_SUM_31',
 'CODE_36_SUM_90',
 'CODE_37_MAX_180',
 'CODE_37_MAX_31',
 'CODE_37_MAX_90',
 'CODE_37_MEAN_180',
 'CODE_37_MEAN_31',
 'CODE_37_MEAN_90',
 'CODE_37_N_180',
 'CODE_37_N_31',
 'CODE_37_N_90',
 'CODE_37_SUM_180',
 'CODE_37_SUM_31',
 'CODE_37_SUM_90',
 'CODE_38_MAX_180',
 'CODE_38_MAX_31',
 'CODE_38_MAX_90',
 'CODE_38_MEAN_180',
 'CODE_38_MEAN_31',
 'CODE_38_MEAN_90',
 'CODE_38_N_180',
 'CODE_38_N_31',
 'CODE_38_N_90',
 'CODE_38_SUM_180',
 'CODE_38_SUM_31',
 'CODE_38_SUM_90',
 'CODE_39_MAX_180',
 'CODE_39_MAX_31',
 'CODE_39_MAX_7',
 'CODE_39_MAX_90',
 'CODE_39_MEAN_180',
 'CODE_39_MEAN_31',
 'CODE_39_MEAN_7',
 'CODE_39_MEAN_90',
 'CODE_39_N_180',
 'CODE_39_N_31',
 'CODE_39_N_7',
 'CODE_39_N_90',
 'CODE_39_SUM_180',
 'CODE_39_SUM_31',
 'CODE_39_SUM_7',
 'CODE_39_SUM_90',
 'CODE_4_MAX_180',
 'CODE_4_MAX_31',
 'CODE_4_MAX_90',
 'CODE_4_MEAN_180',
 'CODE_4_MEAN_31',
 'CODE_4_MEAN_90',
 'CODE_4_N_180',
 'CODE_4_N_31',
 'CODE_4_N_90',
 'CODE_4_SUM_180',
 'CODE_4_SUM_31',
 'CODE_4_SUM_90',
 'CODE_40_MAX_180',
 'CODE_40_MAX_90',
 'CODE_40_MEAN_180',
 'CODE_40_MEAN_90',
 'CODE_40_N_180',
 'CODE_40_N_90',
 'CODE_40_SUM_180',
 'CODE_40_SUM_90',
 'CODE_41_MAX_180',
 'CODE_41_MAX_90',
 'CODE_41_MEAN_180',
 'CODE_41_MEAN_90',
 'CODE_41_N_180',
 'CODE_41_N_90',
 'CODE_41_SUM_180',
 'CODE_41_SUM_90',
 'CODE_42_MAX_180',
 'CODE_42_MAX_31',
 'CODE_42_MAX_90',
 'CODE_42_MEAN_180',
 'CODE_42_MEAN_31',
 'CODE_42_MEAN_90',
 'CODE_42_N_180',
 'CODE_42_N_31',
 'CODE_42_N_90',
 'CODE_42_SUM_180',
 'CODE_42_SUM_31',
 'CODE_42_SUM_90',
 'CODE_43_MAX_180',
 'CODE_43_MAX_31',
 'CODE_43_MAX_90',
 'CODE_43_MEAN_180',
 'CODE_43_MEAN_31',
 'CODE_43_MEAN_90',
 'CODE_43_N_180',
 'CODE_43_N_31',
 'CODE_43_N_90',
 'CODE_43_SUM_180',
 'CODE_43_SUM_31',
 'CODE_43_SUM_90',
 'CODE_44_MAX_180',
 'CODE_44_MAX_31',
 'CODE_44_MAX_90',
 'CODE_44_MEAN_180',
 'CODE_44_MEAN_31',
 'CODE_44_MEAN_90',
 'CODE_44_N_180',
 'CODE_44_N_31',
 'CODE_44_N_90',
 'CODE_44_SUM_180',
 'CODE_44_SUM_31',
 'CODE_44_SUM_90',
 'CODE_45_MAX_180',
 'CODE_45_MAX_31',
 'CODE_45_MAX_90',
 'CODE_45_MEAN_180',
 'CODE_45_MEAN_31',
 'CODE_45_MEAN_90',
 'CODE_45_N_180',
 'CODE_45_N_31',
 'CODE_45_N_90',
 'CODE_45_SUM_180',
 'CODE_45_SUM_31',
 'CODE_45_SUM_90',
 'CODE_46_MAX_180',
 'CODE_46_MAX_31',
 'CODE_46_MAX_7',
 'CODE_46_MAX_90',
 'CODE_46_MEAN_180',
 'CODE_46_MEAN_31',
 'CODE_46_MEAN_7',
 'CODE_46_MEAN_90',
 'CODE_46_N_180',
 'CODE_46_N_31',
 'CODE_46_N_7',
 'CODE_46_N_90',
 'CODE_46_SUM_180',
 'CODE_46_SUM_31',
 'CODE_46_SUM_7',
 'CODE_46_SUM_90',
 'CODE_47_MAX_180',
 'CODE_47_MAX_31',
 'CODE_47_MAX_90',
 'CODE_47_MEAN_180',
 'CODE_47_MEAN_31',
 'CODE_47_MEAN_90',
 'CODE_47_N_180',
 'CODE_47_N_31',
 'CODE_47_N_90',
 'CODE_47_SUM_180',
 'CODE_47_SUM_31',
 'CODE_47_SUM_90',
 'CODE_48_MAX_180',
 'CODE_48_MEAN_180',
 'CODE_48_N_180',
 'CODE_48_SUM_180',
 'CODE_49_MAX_180',
 'CODE_49_MAX_31',
 'CODE_49_MAX_7',
 'CODE_49_MAX_90',
 'CODE_49_MEAN_180',
 'CODE_49_MEAN_31',
 'CODE_49_MEAN_7',
 'CODE_49_MEAN_90',
 'CODE_49_N_180',
 'CODE_49_N_31',
 'CODE_49_N_7',
 'CODE_49_N_90',
 'CODE_49_SUM_180',
 'CODE_49_SUM_31',
 'CODE_49_SUM_7',
 'CODE_49_SUM_90',
 'CODE_5_MAX_180',
 'CODE_5_MAX_90',
 'CODE_5_MEAN_180',
 'CODE_5_MEAN_90',
 'CODE_5_N_180',
 'CODE_5_N_90',
 'CODE_5_SUM_180',
 'CODE_5_SUM_90',
 'CODE_52_MAX_180',
 'CODE_52_MAX_31',
 'CODE_52_MAX_90',
 'CODE_52_MEAN_180',
 'CODE_52_MEAN_31',
 'CODE_52_MEAN_90',
 'CODE_52_N_180',
 'CODE_52_N_31',
 'CODE_52_N_90',
 'CODE_52_SUM_180',
 'CODE_52_SUM_31',
 'CODE_52_SUM_90',
 'CODE_53_MAX_180',
 'CODE_53_MAX_31',
 'CODE_53_MAX_90',
 'CODE_53_MEAN_180',
 'CODE_53_MEAN_31',
 'CODE_53_MEAN_90',
 'CODE_53_N_180',
 'CODE_53_N_31',
 'CODE_53_N_90',
 'CODE_53_SUM_180',
 'CODE_53_SUM_31',
 'CODE_53_SUM_90',
 'CODE_54_MAX_180',
 'CODE_54_MAX_31',
 'CODE_54_MAX_90',
 'CODE_54_MEAN_180',
 'CODE_54_MEAN_31',
 'CODE_54_MEAN_90',
 'CODE_54_N_180',
 'CODE_54_N_31',
 'CODE_54_N_90',
 'CODE_54_SUM_180',
 'CODE_54_SUM_31',
 'CODE_54_SUM_90',
 'CODE_55_MAX_180',
 'CODE_55_MAX_90',
 'CODE_55_MEAN_180',
 'CODE_55_MEAN_90',
 'CODE_55_N_180',
 'CODE_55_N_90',
 'CODE_55_SUM_180',
 'CODE_55_SUM_90',
 'CODE_56_MAX_180',
 'CODE_56_MAX_31',
 'CODE_56_MAX_90',
 'CODE_56_MEAN_180',
 'CODE_56_MEAN_31',
 'CODE_56_MEAN_90',
 'CODE_56_N_180',
 'CODE_56_N_31',
 'CODE_56_N_90',
 'CODE_56_SUM_180',
 'CODE_56_SUM_31',
 'CODE_56_SUM_90',
 'CODE_57_MAX_180',
 'CODE_57_MAX_31',
 'CODE_57_MAX_90',
 'CODE_57_MEAN_180',
 'CODE_57_MEAN_31',
 'CODE_57_MEAN_90',
 'CODE_57_N_180',
 'CODE_57_N_31',
 'CODE_57_N_90',
 'CODE_57_SUM_180',
 'CODE_57_SUM_31',
 'CODE_57_SUM_90',
 'CODE_58_MAX_180',
 'CODE_58_MAX_90',
 'CODE_58_MEAN_180',
 'CODE_58_MEAN_90',
 'CODE_58_N_180',
 'CODE_58_N_90',
 'CODE_58_SUM_180',
 'CODE_58_SUM_90',
 'CODE_59_MAX_180',
 'CODE_59_MAX_31',
 'CODE_59_MAX_90',
 'CODE_59_MEAN_180',
 'CODE_59_MEAN_31',
 'CODE_59_MEAN_90',
 'CODE_59_N_180',
 'CODE_59_N_31',
 'CODE_59_N_90',
 'CODE_59_SUM_180',
 'CODE_59_SUM_31',
 'CODE_59_SUM_90',
 'CODE_6_MAX_180',
 'CODE_6_MAX_31',
 'CODE_6_MAX_90',
 'CODE_6_MEAN_180',
 'CODE_6_MEAN_31',
 'CODE_6_MEAN_90',
 'CODE_6_N_180',
 'CODE_6_N_31',
 'CODE_6_N_90',
 'CODE_6_SUM_180',
 'CODE_6_SUM_31',
 'CODE_6_SUM_90',
 'CODE_60_MAX_180',
 'CODE_60_MAX_31',
 'CODE_60_MAX_90',
 'CODE_60_MEAN_180',
 'CODE_60_MEAN_31',
 'CODE_60_MEAN_90',
 'CODE_60_N_180',
 'CODE_60_N_31',
 'CODE_60_N_90',
 'CODE_60_SUM_180',
 'CODE_60_SUM_31',
 'CODE_60_SUM_90',
 'CODE_61_MAX_180',
 'CODE_61_MAX_31',
 'CODE_61_MAX_90',
 'CODE_61_MEAN_180',
 'CODE_61_MEAN_31',
 'CODE_61_MEAN_90',
 'CODE_61_N_180',
 'CODE_61_N_31',
 'CODE_61_N_90',
 'CODE_61_SUM_180',
 'CODE_61_SUM_31',
 'CODE_61_SUM_90',
 'CODE_62_MAX_180',
 'CODE_62_MAX_31',
 'CODE_62_MAX_90',
 'CODE_62_MEAN_180',
 'CODE_62_MEAN_31',
 'CODE_62_MEAN_90',
 'CODE_62_N_180',
 'CODE_62_N_31',
 'CODE_62_N_90',
 'CODE_62_SUM_180',
 'CODE_62_SUM_31',
 'CODE_62_SUM_90',
 'CODE_63_MAX_180',
 'CODE_63_MAX_31',
 'CODE_63_MAX_7',
 'CODE_63_MAX_90',
 'CODE_63_MEAN_180',
 'CODE_63_MEAN_31',
 'CODE_63_MEAN_7',
 'CODE_63_MEAN_90',
 'CODE_63_N_180',
 'CODE_63_N_31',
 'CODE_63_N_7',
 'CODE_63_N_90',
 'CODE_63_SUM_180',
 'CODE_63_SUM_31',
 'CODE_63_SUM_7',
 'CODE_63_SUM_90',
 'CODE_64_MAX_180',
 'CODE_64_MAX_31',
 'CODE_64_MAX_7',
 'CODE_64_MAX_90',
 'CODE_64_MEAN_180',
 'CODE_64_MEAN_31',
 'CODE_64_MEAN_7',
 'CODE_64_MEAN_90',
 'CODE_64_N_180',
 'CODE_64_N_31',
 'CODE_64_N_7',
 'CODE_64_N_90',
 'CODE_64_SUM_180',
 'CODE_64_SUM_31',
 'CODE_64_SUM_7',
 'CODE_64_SUM_90',
 'CODE_66_MAX_180',
 'CODE_66_MAX_31',
 'CODE_66_MAX_90',
 'CODE_66_MEAN_180',
 'CODE_66_MEAN_31',
 'CODE_66_MEAN_90',
 'CODE_66_N_180',
 'CODE_66_N_31',
 'CODE_66_N_90',
 'CODE_66_SUM_180',
 'CODE_66_SUM_31',
 'CODE_66_SUM_90',
 'CODE_67_MAX_180',
 'CODE_67_MAX_31',
 'CODE_67_MAX_7',
 'CODE_67_MAX_90',
 'CODE_67_MEAN_180',
 'CODE_67_MEAN_31',
 'CODE_67_MEAN_7',
 'CODE_67_MEAN_90',
 'CODE_67_N_180',
 'CODE_67_N_31',
 'CODE_67_N_7',
 'CODE_67_N_90',
 'CODE_67_SUM_180',
 'CODE_67_SUM_31',
 'CODE_67_SUM_7',
 'CODE_67_SUM_90',
 'CODE_68_MAX_180',
 'CODE_68_MAX_31',
 'CODE_68_MAX_90',
 'CODE_68_MEAN_180',
 'CODE_68_MEAN_31',
 'CODE_68_MEAN_90',
 'CODE_68_N_180',
 'CODE_68_N_31',
 'CODE_68_N_90',
 'CODE_68_SUM_180',
 'CODE_68_SUM_31',
 'CODE_68_SUM_90',
 'CODE_69_MAX_180',
 'CODE_69_MAX_31',
 'CODE_69_MAX_90',
 'CODE_69_MEAN_180',
 'CODE_69_MEAN_31',
 'CODE_69_MEAN_90',
 'CODE_69_N_180',
 'CODE_69_N_31',
 'CODE_69_N_90',
 'CODE_69_SUM_180',
 'CODE_69_SUM_31',
 'CODE_69_SUM_90',
 'CODE_7_MAX_180',
 'CODE_7_MAX_31',
 'CODE_7_MAX_90',
 'CODE_7_MEAN_180',
 'CODE_7_MEAN_31',
 'CODE_7_MEAN_90',
 'CODE_7_N_180',
 'CODE_7_N_31',
 'CODE_7_N_90',
 'CODE_7_SUM_180',
 'CODE_7_SUM_31',
 'CODE_7_SUM_90',
 'CODE_8_MAX_180',
 'CODE_8_MAX_31',
 'CODE_8_MAX_90',
 'CODE_8_MEAN_180',
 'CODE_8_MEAN_31',
 'CODE_8_MEAN_90',
 'CODE_8_N_180',
 'CODE_8_N_31',
 'CODE_8_N_90',
 'CODE_8_SUM_180',
 'CODE_8_SUM_31',
 'CODE_8_SUM_90',
 'CODE_9_MAX_180',
 'CODE_9_MAX_31',
 'CODE_9_MAX_90',
 'CODE_9_MEAN_180',
 'CODE_9_MEAN_31',
 'CODE_9_MEAN_90',
 'CODE_9_N_180',
 'CODE_9_N_31',
 'CODE_9_N_90',
 'CODE_9_SUM_180',
 'CODE_9_SUM_31',
 'CODE_9_SUM_90',
 'CODE_NA_MAX_180',
 'CODE_NA_MAX_31',
 'CODE_NA_MAX_7',
 'CODE_NA_MAX_90',
 'CODE_NA_MEAN_180',
 'CODE_NA_MEAN_31',
 'CODE_NA_MEAN_7',
 'CODE_NA_MEAN_90',
 'CODE_NA_N_180',
 'CODE_NA_N_31',
 'CODE_NA_N_7',
 'CODE_NA_N_90',
 'CODE_NA_SUM_180',
 'CODE_NA_SUM_31',
 'CODE_NA_SUM_7',
 'CODE_NA_SUM_90',
 'TOTAL_MAX_180',
 'TOTAL_MAX_31',
 'TOTAL_MAX_7',
 'TOTAL_MAX_90',
 'TOTAL_MEAN_180',
 'TOTAL_MEAN_31',
 'TOTAL_MEAN_7',
 'TOTAL_MEAN_90',
 'TOTAL_N_180',
 'TOTAL_N_31',
 'TOTAL_N_7',
 'TOTAL_N_90',
 'TOTAL_SUM_180',
 'TOTAL_SUM_31',
 'TOTAL_SUM_7',
 'TOTAL_SUM_90',
 'TXN_CHN_15V_MAX_180',
 'TXN_CHN_15V_MAX_90',
 'TXN_CHN_15V_MEAN_180',
 'TXN_CHN_15V_MEAN_90',
 'TXN_CHN_15V_N_180',
 'TXN_CHN_15V_N_90',
 'TXN_CHN_15V_SUM_180',
 'TXN_CHN_15V_SUM_90',
 'TXN_CHN_33213P_MAX_180',
 'TXN_CHN_33213P_MAX_31',
 'TXN_CHN_33213P_MAX_90',
 'TXN_CHN_33213P_MEAN_180',
 'TXN_CHN_33213P_MEAN_31',
 'TXN_CHN_33213P_MEAN_90',
 'TXN_CHN_33213P_N_180',
 'TXN_CHN_33213P_N_31',
 'TXN_CHN_33213P_N_90',
 'TXN_CHN_33213P_SUM_180',
 'TXN_CHN_33213P_SUM_31',
 'TXN_CHN_33213P_SUM_90',
 'TXN_CHN_Foreign ATM_MAX_180',
 'TXN_CHN_Foreign ATM_MAX_31',
 'TXN_CHN_Foreign ATM_MAX_90',
 'TXN_CHN_Foreign ATM_MEAN_180',
 'TXN_CHN_Foreign ATM_MEAN_31',
 'TXN_CHN_Foreign ATM_MEAN_90',
 'TXN_CHN_Foreign ATM_N_180',
 'TXN_CHN_Foreign ATM_N_31',
 'TXN_CHN_Foreign ATM_N_90',
 'TXN_CHN_Foreign ATM_SUM_180',
 'TXN_CHN_Foreign ATM_SUM_31',
 'TXN_CHN_Foreign ATM_SUM_90',
 'TXN_CHN_I-bank_MAX_180',
 'TXN_CHN_I-bank_MAX_31',
 'TXN_CHN_I-bank_MAX_7',
 'TXN_CHN_I-bank_MAX_90',
 'TXN_CHN_I-bank_MEAN_180',
 'TXN_CHN_I-bank_MEAN_31',
 'TXN_CHN_I-bank_MEAN_7',
 'TXN_CHN_I-bank_MEAN_90',
 'TXN_CHN_I-bank_N_180',
 'TXN_CHN_I-bank_N_31',
 'TXN_CHN_I-bank_N_7',
 'TXN_CHN_I-bank_N_90',
 'TXN_CHN_I-bank_SUM_180',
 'TXN_CHN_I-bank_SUM_31',
 'TXN_CHN_I-bank_SUM_7',
 'TXN_CHN_I-bank_SUM_90',
 'TXN_CHN_Internet purchase_MAX_180',
 'TXN_CHN_Internet purchase_MAX_31',
 'TXN_CHN_Internet purchase_MAX_7',
 'TXN_CHN_Internet purchase_MAX_90',
 'TXN_CHN_Internet purchase_MEAN_180',
 'TXN_CHN_Internet purchase_MEAN_31',
 'TXN_CHN_Internet purchase_MEAN_7',
 'TXN_CHN_Internet purchase_MEAN_90',
 'TXN_CHN_Internet purchase_N_180',
 'TXN_CHN_Internet purchase_N_31',
 'TXN_CHN_Internet purchase_N_7',
 'TXN_CHN_Internet purchase_N_90',
 'TXN_CHN_Internet purchase_SUM_180',
 'TXN_CHN_Internet purchase_SUM_31',
 'TXN_CHN_Internet purchase_SUM_7',
 'TXN_CHN_Internet purchase_SUM_90',
 'TXN_CHN_Our ATM_MAX_180',

In [150]:
train.columns.difference(['CONTROL_GROUP_FLG', 'SCENARIO_NAME_UNI','TARGET']).tolist()

['11_AddrCity2',
 '11_AddrCountry',
 '12_AddrCity2',
 '12_AddrCountry',
 '13_AddrCity2',
 '13_AddrCountry',
 'BAL',
 'BANK',
 'BIRTH_DATE',
 'CARD_CONTR_COUNT_0',
 'CARD_STATUS_14',
 'CARD_STATUS_176',
 'CLIENT_ID',
 'CL_AMT_DOP',
 'CL_AMT_ZP',
 'CL_AUTO_EX',
 'CL_CCY_DOP',
 'CL_CCY_ZP',
 'CL_EDU',
 'CL_ESTATE_TYPE',
 'CL_FAM_ST',
 'CL_INDUSTR',
 'CL_OFF_POS',
 'CL_OWN_TYPE',
 'CL_SOC_ST',
 'CODE_17_MAX_180',
 'CODE_17_MEAN_180',
 'CODE_17_N_180',
 'CODE_17_SUM_180',
 'CODE_26_MAX_180',
 'CODE_26_MEAN_180',
 'CODE_26_N_180',
 'CODE_26_SUM_180',
 'CODE_2_MAX_180',
 'CODE_2_MEAN_180',
 'CODE_2_N_180',
 'CODE_2_SUM_180',
 'CODE_35_MAX_180',
 'CODE_35_MEAN_180',
 'CODE_35_N_180',
 'CODE_35_SUM_180',
 'CODE_46_MAX_180',
 'CODE_46_MEAN_180',
 'CODE_46_N_180',
 'CODE_46_SUM_180',
 'CODE_59_MAX_180',
 'CODE_59_MEAN_180',
 'CODE_59_N_180',
 'CODE_59_SUM_180',
 'CODE_67_MAX_180',
 'CODE_67_MAX_90',
 'CODE_67_MEAN_180',
 'CODE_67_MEAN_90',
 'CODE_67_N_180',
 'CODE_67_N_90',
 'CODE_67_SUM_180',
 'CODE_67_SUM_90',
 'CODE_NA_MAX_180',
 'CODE_NA_MAX_90',
 'CODE_NA_MEAN_180',
 'CODE_NA_MEAN_90',
 'CODE_NA_N_180',
 'CODE_NA_N_90',
 'CODE_NA_SUM_180',
 'CODE_NA_SUM_90',
 'CONTRACT_REF',
 'FL_4P',
 'FL_CR_PAN',
 'FL_DIR_UCH',
 'FL_DOC_PROFIT',
 'FL_FRGN_TRIP',
 'FL_FRNG_PASSP',
 'FL_GOLD',
 'FL_MOBB',
 'FL_P24',
 'FL_PENS',
 'FL_PENS_DOC',
 'FL_SMSI',
 'FL_SOC',
 'FL_STUD',
 'FL_ZP',
 'Home',
 'IS_LOYALTY_AUTO',
 'LAST_CARD_STATUS',
 'LAST_CARD_STATUS_DT',
 'LAST_CONTR_STATUS_DT',
 'LIM_AVG_CHANGE',
 'LIM_AVG_N_CHANGES',
 'LIM_AVG_N_POS_CHANGE',
 'LIM_AVG_POS_CHANGE',
 'LIM_MAX_POS_CHANGE',
 'LIM_MIN_POS_CHANGE',
 'LIM_RECENT',
 'MEAN_DAYS_DIFF_CHANGE_0',
 'MEAN_STATUS_COUNT_0',
 'Mobile',
 'QTY_CHLD',
 'REP_POPULATION',
 'REP_SEX',
 'START_DATE',
 'TOTAL_BAL_NEG_CHNG_MAX_180',
 'TOTAL_BAL_NEG_CHNG_MAX_31',
 'TOTAL_BAL_NEG_CHNG_MAX_7',
 'TOTAL_BAL_NEG_CHNG_MAX_90',
 'TOTAL_BAL_NEG_CHNG_MIN_180',
 'TOTAL_BAL_NEG_CHNG_MIN_31',
 'TOTAL_BAL_NEG_CHNG_MIN_7',
 'TOTAL_BAL_NEG_CHNG_MIN_90',
 'TOTAL_BAL_NEG_CHNG_N_180',
 'TOTAL_BAL_NEG_CHNG_N_31',
 'TOTAL_BAL_NEG_CHNG_N_7',
 'TOTAL_BAL_NEG_CHNG_N_90',
 'TOTAL_BAL_NEG_CHNG_SUM_180',
 'TOTAL_BAL_NEG_CHNG_SUM_31',
 'TOTAL_BAL_NEG_CHNG_SUM_7',
 'TOTAL_BAL_NEG_CHNG_SUM_90',
 'TOTAL_BAL_POS_CHNG_MAX_180',
 'TOTAL_BAL_POS_CHNG_MAX_31',
 'TOTAL_BAL_POS_CHNG_MAX_7',
 'TOTAL_BAL_POS_CHNG_MAX_90',
 'TOTAL_BAL_POS_CHNG_MIN_180',
 'TOTAL_BAL_POS_CHNG_MIN_31',
 'TOTAL_BAL_POS_CHNG_MIN_7',
 'TOTAL_BAL_POS_CHNG_MIN_90',
 'TOTAL_BAL_POS_CHNG_N_180',
 'TOTAL_BAL_POS_CHNG_N_31',
 'TOTAL_BAL_POS_CHNG_N_7',
 'TOTAL_BAL_POS_CHNG_N_90',
 'TOTAL_BAL_POS_CHNG_SUM_180',
 'TOTAL_BAL_POS_CHNG_SUM_31',
 'TOTAL_BAL_POS_CHNG_SUM_7',
 'TOTAL_BAL_POS_CHNG_SUM_90',
 'TOTAL_DEBT_NEG_CHNG_MAX_180',
 'TOTAL_DEBT_NEG_CHNG_MIN_180',
 'TOTAL_DEBT_NEG_CHNG_N_180',
 'TOTAL_DEBT_NEG_CHNG_SUM_180',
 'TOTAL_DEBT_POS_CHNG_MAX_180',
 'TOTAL_DEBT_POS_CHNG_MIN_180',
 'TOTAL_DEBT_POS_CHNG_N_180',
 'TOTAL_DEBT_POS_CHNG_SUM_180',
 'TOTAL_MAX_180',
 'TOTAL_MAX_31',
 'TOTAL_MAX_90',
 'TOTAL_MEAN_180',
 'TOTAL_MEAN_31',
 'TOTAL_MEAN_90',
 'TOTAL_N_180',
 'TOTAL_N_31',
 'TOTAL_N_90',
 'TOTAL_SUM_180',
 'TOTAL_SUM_31',
 'TOTAL_SUM_90',
 'TXN_CHN_Internet purchase_MAX_180',
 'TXN_CHN_Internet purchase_MAX_90',
 'TXN_CHN_Internet purchase_MEAN_180',
 'TXN_CHN_Internet purchase_MEAN_90',
 'TXN_CHN_Internet purchase_N_180',
 'TXN_CHN_Internet purchase_N_90',
 'TXN_CHN_Internet purchase_SUM_180',
 'TXN_CHN_Internet purchase_SUM_90',
 'TXN_CHN_Our ATM_MAX_180',
 'TXN_CHN_Our ATM_MEAN_180',
 'TXN_CHN_Our ATM_N_180',
 'TXN_CHN_Our ATM_SUM_180',
 'TXN_CHN_POS terminal_MAX_180',
 'TXN_CHN_POS terminal_MAX_31',
 'TXN_CHN_POS terminal_MAX_90',
 'TXN_CHN_POS terminal_MEAN_180',
 'TXN_CHN_POS terminal_MEAN_31',
 'TXN_CHN_POS terminal_MEAN_90',
 'TXN_CHN_POS terminal_N_180',
 'TXN_CHN_POS terminal_N_31',
 'TXN_CHN_POS terminal_N_90',
 'TXN_CHN_POS terminal_SUM_180',
 'TXN_CHN_POS terminal_SUM_31',
 'TXN_CHN_POS terminal_SUM_90',
 'TXN_CHN_Unknown_MAX_180',
 'TXN_CHN_Unknown_MEAN_180',
 'TXN_CHN_Unknown_N_180',
 'TXN_CHN_Unknown_SUM_180',
 'TXN_TP_ATM_MAX_180',
 'TXN_TP_ATM_MEAN_180',
 'TXN_TP_ATM_N_180',
 'TXN_TP_ATM_SUM_180',
 'TXN_TP_Credit_MAX_180',
 'TXN_TP_Credit_MAX_90',
 'TXN_TP_Credit_MEAN_180',
 'TXN_TP_Credit_MEAN_90',
 'TXN_TP_Credit_N_180',
 'TXN_TP_Credit_N_90',
 'TXN_TP_Credit_SUM_180',
 'TXN_TP_Credit_SUM_90',
 'TXN_TP_MT_MAX_180',
 'TXN_TP_MT_MEAN_180',
 'TXN_TP_MT_N_180',
 'TXN_TP_MT_SUM_180',
 'TXN_TP_POS_MAX_180',
 'TXN_TP_POS_MAX_31',
 'TXN_TP_POS_MAX_90',
 'TXN_TP_POS_MEAN_180',
 'TXN_TP_POS_MEAN_31',
 'TXN_TP_POS_MEAN_90',
 'TXN_TP_POS_N_180',
 'TXN_TP_POS_N_31',
 'TXN_TP_POS_N_90',
 'TXN_TP_POS_SUM_180',
 'TXN_TP_POS_SUM_31',
 'TXN_TP_POS_SUM_90',
 'TXN_TP_Purposeful credit_MAX_180',
 'TXN_TP_Purposeful credit_MEAN_180',
 'TXN_TP_Purposeful credit_N_180',
 'TXN_TP_Purposeful credit_SUM_180']

In [151]:
test = test.merge(losted_test, left_index=True, right_index=True)\
    [train.columns.difference(['CONTROL_GROUP_FLG', 'SCENARIO_NAME_UNI','TARGET']).tolist()]

In [153]:
train.head()

,CONTRACT_REF,CLIENT_ID,CONTROL_GROUP_FLG,START_DATE,TARGET,11_AddrCity2,11_AddrCountry,12_AddrCity2,12_AddrCountry,13_AddrCity2,...,TXN_TP_POS_N_180,TXN_TP_POS_N_31,TXN_TP_POS_N_90,TXN_TP_POS_SUM_180,TXN_TP_POS_SUM_31,TXN_TP_POS_SUM_90,TXN_TP_Purposeful credit_MAX_180,TXN_TP_Purposeful credit_MEAN_180,TXN_TP_Purposeful credit_N_180,TXN_TP_Purposeful credit_SUM_180
0,273-P-99431598,105098373,N,2017-01-23,1,ГОРЯЧИЙКЛЮЧ,RU,ГОРЯЧИЙКЛЮЧ,RU,КАМЫШИН,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,274-P-23967129,101763714,N,2017-04-08,1,МУРМАНСК,RU,МУРМАНСК,RU,АХТУБИНСК,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,274-P-67223249,104216626,N,2017-01-23,1,СОСНОВЫЙБОР,RU,СОСНОВЫЙБОР,RU,ВЕРХНИЕРУДИЦЫ,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,273-P-51055302,102113400,N,2016-12-15,1,РОСТОВНАДОНУ,RU,РОСТОВНАДОНУ,RU,РОСТОВНАДОНУ,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,271-P-09670370,101989621,N,2017-01-19,1,ЛИПЕЦК,RU,ЛИПЕЦК,RU,СТУПИНО,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [166]:
train.shape

(114720, 215)

In [167]:
test.head()

,11_AddrCity2,11_AddrCountry,12_AddrCity2,12_AddrCountry,13_AddrCity2,13_AddrCountry,BAL,BANK,BIRTH_DATE,CARD_CONTR_COUNT_0,...,TXN_TP_POS_N_180,TXN_TP_POS_N_31,TXN_TP_POS_N_90,TXN_TP_POS_SUM_180,TXN_TP_POS_SUM_31,TXN_TP_POS_SUM_90,TXN_TP_Purposeful credit_MAX_180,TXN_TP_Purposeful credit_MEAN_180,TXN_TP_Purposeful credit_N_180,TXN_TP_Purposeful credit_SUM_180
0,0.0,0.0,0.0,0.0,0.0,0.0,304.83,BBKK,1989-02-03,3,...,0,0,0,0.00,0.0,0.0,0.0,0.0,0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.00,BBKK,NaN,1,...,0,0,0,0.00,0.0,0.0,0.0,0.0,0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.00,BBKK,NaN,2,...,0,0,0,0.00,0.0,0.0,0.0,0.0,0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,670.22,BBKK,NaN,5,...,8,0,2,21872.81,0.0,1600.0,0.0,0.0,0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,-55474.52,BBKK,NaN,4,...,0,0,0,0.00,0.0,0.0,0.0,0.0,0,0.0

In [161]:
print(test.shape)
test.head()

(79544, 212)

,11_AddrCity2,11_AddrCountry,12_AddrCity2,12_AddrCountry,13_AddrCity2,13_AddrCountry,BAL,BANK,BIRTH_DATE,CARD_CONTR_COUNT_0,...,TXN_TP_POS_N_180,TXN_TP_POS_N_31,TXN_TP_POS_N_90,TXN_TP_POS_SUM_180,TXN_TP_POS_SUM_31,TXN_TP_POS_SUM_90,TXN_TP_Purposeful credit_MAX_180,TXN_TP_Purposeful credit_MEAN_180,TXN_TP_Purposeful credit_N_180,TXN_TP_Purposeful credit_SUM_180
0,0.0,0.0,0.0,0.0,0.0,0.0,304.83,BBKK,1989-02-03,3,...,0,0,0,0.00,0.0,0.0,0.0,0.0,0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.00,BBKK,NaN,1,...,0,0,0,0.00,0.0,0.0,0.0,0.0,0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.00,BBKK,NaN,2,...,0,0,0,0.00,0.0,0.0,0.0,0.0,0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,670.22,BBKK,NaN,5,...,8,0,2,21872.81,0.0,1600.0,0.0,0.0,0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,-55474.52,BBKK,NaN,4,...,0,0,0,0.00,0.0,0.0,0.0,0.0,0,0.0

In [157]:
set(train.columns) - set(test.columns)

{'CONTROL_GROUP_FLG', 'SCENARIO_NAME_UNI', 'TARGET'}

In [158]:
set(test.columns) - set(train.columns)

set()

In [120]:
test.to_csv('./test_data/test_data_05_2018/test_data_05_2018.csv', 
            index=False, sep='>', na_rep='<null>', encoding='utf-8')

In [77]:
#  many new cols - ?

In [129]:
np.mean(test['BIRTH_DATE'].isnull().values)

0.86690385195615

In [164]:
train.columns.tolist()

['CONTRACT_REF',
 'CLIENT_ID',
 'CONTROL_GROUP_FLG',
 'START_DATE',
 'TARGET',
 '11_AddrCity2',
 '11_AddrCountry',
 '12_AddrCity2',
 '12_AddrCountry',
 '13_AddrCity2',
 '13_AddrCountry',
 'BAL',
 'BANK',
 'BIRTH_DATE',
 'CARD_CONTR_COUNT_0',
 'CARD_STATUS_14',
 'CARD_STATUS_176',
 'CL_AMT_DOP',
 'CL_AMT_ZP',
 'CL_AUTO_EX',
 'CL_CCY_DOP',
 'CL_CCY_ZP',
 'CL_EDU',
 'CL_ESTATE_TYPE',
 'CL_FAM_ST',
 'CL_INDUSTR',
 'CL_OFF_POS',
 'CL_OWN_TYPE',
 'CL_SOC_ST',
 'CODE_17_MAX_180',
 'CODE_17_MEAN_180',
 'CODE_17_N_180',
 'CODE_17_SUM_180',
 'CODE_26_MAX_180',
 'CODE_26_MEAN_180',
 'CODE_26_N_180',
 'CODE_26_SUM_180',
 'CODE_2_MAX_180',
 'CODE_2_MEAN_180',
 'CODE_2_N_180',
 'CODE_2_SUM_180',
 'CODE_35_MAX_180',
 'CODE_35_MEAN_180',
 'CODE_35_N_180',
 'CODE_35_SUM_180',
 'CODE_46_MAX_180',
 'CODE_46_MEAN_180',
 'CODE_46_N_180',
 'CODE_46_SUM_180',
 'CODE_59_MAX_180',
 'CODE_59_MEAN_180',
 'CODE_59_N_180',
 'CODE_59_SUM_180',
 'CODE_67_MAX_180',
 'CODE_67_MAX_90',
 'CODE_67_MEAN_180',
 'CODE_67_MEAN_90',
 'CODE_67_N_180',
 'CODE_67_N_90',
 'CODE_67_SUM_180',
 'CODE_67_SUM_90',
 'CODE_NA_MAX_180',
 'CODE_NA_MAX_90',
 'CODE_NA_MEAN_180',
 'CODE_NA_MEAN_90',
 'CODE_NA_N_180',
 'CODE_NA_N_90',
 'CODE_NA_SUM_180',
 'CODE_NA_SUM_90',
 'FL_4P',
 'FL_CR_PAN',
 'FL_DIR_UCH',
 'FL_DOC_PROFIT',
 'FL_FRGN_TRIP',
 'FL_FRNG_PASSP',
 'FL_GOLD',
 'FL_MOBB',
 'FL_P24',
 'FL_PENS',
 'FL_PENS_DOC',
 'FL_SMSI',
 'FL_SOC',
 'FL_STUD',
 'FL_ZP',
 'Home',
 'IS_LOYALTY_AUTO',
 'LAST_CARD_STATUS',
 'LAST_CARD_STATUS_DT',
 'LAST_CONTR_STATUS_DT',
 'LIM_AVG_CHANGE',
 'LIM_AVG_N_CHANGES',
 'LIM_AVG_N_POS_CHANGE',
 'LIM_AVG_POS_CHANGE',
 'LIM_MAX_POS_CHANGE',
 'LIM_MIN_POS_CHANGE',
 'LIM_RECENT',
 'MEAN_DAYS_DIFF_CHANGE_0',
 'MEAN_STATUS_COUNT_0',
 'Mobile',
 'QTY_CHLD',
 'REP_POPULATION',
 'REP_SEX',
 'SCENARIO_NAME_UNI',
 'TOTAL_BAL_NEG_CHNG_MAX_180',
 'TOTAL_BAL_NEG_CHNG_MAX_31',
 'TOTAL_BAL_NEG_CHNG_MAX_7',
 'TOTAL_BAL_NEG_CHNG_MAX_90',
 'TOTAL_BAL_NEG_CHNG_MIN_180',
 'TOTAL_BAL_NEG_CHNG_MIN_31',
 'TOTAL_BAL_NEG_CHNG_MIN_7',
 'TOTAL_BAL_NEG_CHNG_MIN_90',
 'TOTAL_BAL_NEG_CHNG_N_180',
 'TOTAL_BAL_NEG_CHNG_N_31',
 'TOTAL_BAL_NEG_CHNG_N_7',
 'TOTAL_BAL_NEG_CHNG_N_90',
 'TOTAL_BAL_NEG_CHNG_SUM_180',
 'TOTAL_BAL_NEG_CHNG_SUM_31',
 'TOTAL_BAL_NEG_CHNG_SUM_7',
 'TOTAL_BAL_NEG_CHNG_SUM_90',
 'TOTAL_BAL_POS_CHNG_MAX_180',
 'TOTAL_BAL_POS_CHNG_MAX_31',
 'TOTAL_BAL_POS_CHNG_MAX_7',
 'TOTAL_BAL_POS_CHNG_MAX_90',
 'TOTAL_BAL_POS_CHNG_MIN_180',
 'TOTAL_BAL_POS_CHNG_MIN_31',
 'TOTAL_BAL_POS_CHNG_MIN_7',
 'TOTAL_BAL_POS_CHNG_MIN_90',
 'TOTAL_BAL_POS_CHNG_N_180',
 'TOTAL_BAL_POS_CHNG_N_31',
 'TOTAL_BAL_POS_CHNG_N_7',
 'TOTAL_BAL_POS_CHNG_N_90',
 'TOTAL_BAL_POS_CHNG_SUM_180',
 'TOTAL_BAL_POS_CHNG_SUM_31',
 'TOTAL_BAL_POS_CHNG_SUM_7',
 'TOTAL_BAL_POS_CHNG_SUM_90',
 'TOTAL_DEBT_NEG_CHNG_MAX_180',
 'TOTAL_DEBT_NEG_CHNG_MIN_180',
 'TOTAL_DEBT_NEG_CHNG_N_180',
 'TOTAL_DEBT_NEG_CHNG_SUM_180',
 'TOTAL_DEBT_POS_CHNG_MAX_180',
 'TOTAL_DEBT_POS_CHNG_MIN_180',
 'TOTAL_DEBT_POS_CHNG_N_180',
 'TOTAL_DEBT_POS_CHNG_SUM_180',
 'TOTAL_MAX_180',
 'TOTAL_MAX_31',
 'TOTAL_MAX_90',
 'TOTAL_MEAN_180',
 'TOTAL_MEAN_31',
 'TOTAL_MEAN_90',
 'TOTAL_N_180',
 'TOTAL_N_31',
 'TOTAL_N_90',
 'TOTAL_SUM_180',
 'TOTAL_SUM_31',
 'TOTAL_SUM_90',
 'TXN_CHN_Internet purchase_MAX_180',
 'TXN_CHN_Internet purchase_MAX_90',
 'TXN_CHN_Internet purchase_MEAN_180',
 'TXN_CHN_Internet purchase_MEAN_90',
 'TXN_CHN_Internet purchase_N_180',
 'TXN_CHN_Internet purchase_N_90',
 'TXN_CHN_Internet purchase_SUM_180',
 'TXN_CHN_Internet purchase_SUM_90',
 'TXN_CHN_Our ATM_MAX_180',
 'TXN_CHN_Our ATM_MEAN_180',
 'TXN_CHN_Our ATM_N_180',
 'TXN_CHN_Our ATM_SUM_180',
 'TXN_CHN_POS terminal_MAX_180',
 'TXN_CHN_POS terminal_MAX_31',
 'TXN_CHN_POS terminal_MAX_90',
 'TXN_CHN_POS terminal_MEAN_180',
 'TXN_CHN_POS terminal_MEAN_31',
 'TXN_CHN_POS terminal_MEAN_90',
 'TXN_CHN_POS terminal_N_180',
 'TXN_CHN_POS terminal_N_31',
 'TXN_CHN_POS terminal_N_90',
 'TXN_CHN_POS terminal_SUM_180',
 'TXN_CHN_POS terminal_SUM_31',
 'TXN_CHN_POS terminal_SUM_90',
 'TXN_CHN_Unknown_MAX_180',
 'TXN_CHN_Unknown_MEAN_180',
 'TXN_CHN_Unknown_N_180',
 'TXN_CHN_Unknown_SUM_180',
 'TXN_TP_ATM_MAX_180',
 'TXN_TP_ATM_MEAN_180',
 'TXN_TP_ATM_N_180',
 'TXN_TP_ATM_SUM_180',
 'TXN_TP_Credit_MAX_180',
 'TXN_TP_Credit_MAX_90',
 'TXN_TP_Credit_MEAN_180',
 'TXN_TP_Credit_MEAN_90',
 'TXN_TP_Credit_N_180',
 'TXN_TP_Credit_N_90',
 'TXN_TP_Credit_SUM_180',
 'TXN_TP_Credit_SUM_90',
 'TXN_TP_MT_MAX_180',
 'TXN_TP_MT_MEAN_180',
 'TXN_TP_MT_N_180',
 'TXN_TP_MT_SUM_180',
 'TXN_TP_POS_MAX_180',
 'TXN_TP_POS_MAX_31',
 'TXN_TP_POS_MAX_90',
 'TXN_TP_POS_MEAN_180',
 'TXN_TP_POS_MEAN_31',
 'TXN_TP_POS_MEAN_90',
 'TXN_TP_POS_N_180',
 'TXN_TP_POS_N_31',
 'TXN_TP_POS_N_90',
 'TXN_TP_POS_SUM_180',
 'TXN_TP_POS_SUM_31',
 'TXN_TP_POS_SUM_90',
 'TXN_TP_Purposeful credit_MAX_180',
 'TXN_TP_Purposeful credit_MEAN_180',
 'TXN_TP_Purposeful credit_N_180',
 'TXN_TP_Purposeful credit_SUM_180']

In [165]:
test.columns.tolist()

['11_AddrCity2',
 '11_AddrCountry',
 '12_AddrCity2',
 '12_AddrCountry',
 '13_AddrCity2',
 '13_AddrCountry',
 'BAL',
 'BANK',
 'BIRTH_DATE',
 'CARD_CONTR_COUNT_0',
 'CARD_STATUS_14',
 'CARD_STATUS_176',
 'CLIENT_ID',
 'CL_AMT_DOP',
 'CL_AMT_ZP',
 'CL_AUTO_EX',
 'CL_CCY_DOP',
 'CL_CCY_ZP',
 'CL_EDU',
 'CL_ESTATE_TYPE',
 'CL_FAM_ST',
 'CL_INDUSTR',
 'CL_OFF_POS',
 'CL_OWN_TYPE',
 'CL_SOC_ST',
 'CODE_17_MAX_180',
 'CODE_17_MEAN_180',
 'CODE_17_N_180',
 'CODE_17_SUM_180',
 'CODE_26_MAX_180',
 'CODE_26_MEAN_180',
 'CODE_26_N_180',
 'CODE_26_SUM_180',
 'CODE_2_MAX_180',
 'CODE_2_MEAN_180',
 'CODE_2_N_180',
 'CODE_2_SUM_180',
 'CODE_35_MAX_180',
 'CODE_35_MEAN_180',
 'CODE_35_N_180',
 'CODE_35_SUM_180',
 'CODE_46_MAX_180',
 'CODE_46_MEAN_180',
 'CODE_46_N_180',
 'CODE_46_SUM_180',
 'CODE_59_MAX_180',
 'CODE_59_MEAN_180',
 'CODE_59_N_180',
 'CODE_59_SUM_180',
 'CODE_67_MAX_180',
 'CODE_67_MAX_90',
 'CODE_67_MEAN_180',
 'CODE_67_MEAN_90',
 'CODE_67_N_180',
 'CODE_67_N_90',
 'CODE_67_SUM_180',
 'CODE_67_SUM_90',
 'CODE_NA_MAX_180',
 'CODE_NA_MAX_90',
 'CODE_NA_MEAN_180',
 'CODE_NA_MEAN_90',
 'CODE_NA_N_180',
 'CODE_NA_N_90',
 'CODE_NA_SUM_180',
 'CODE_NA_SUM_90',
 'CONTRACT_REF',
 'FL_4P',
 'FL_CR_PAN',
 'FL_DIR_UCH',
 'FL_DOC_PROFIT',
 'FL_FRGN_TRIP',
 'FL_FRNG_PASSP',
 'FL_GOLD',
 'FL_MOBB',
 'FL_P24',
 'FL_PENS',
 'FL_PENS_DOC',
 'FL_SMSI',
 'FL_SOC',
 'FL_STUD',
 'FL_ZP',
 'Home',
 'IS_LOYALTY_AUTO',
 'LAST_CARD_STATUS',
 'LAST_CARD_STATUS_DT',
 'LAST_CONTR_STATUS_DT',
 'LIM_AVG_CHANGE',
 'LIM_AVG_N_CHANGES',
 'LIM_AVG_N_POS_CHANGE',
 'LIM_AVG_POS_CHANGE',
 'LIM_MAX_POS_CHANGE',
 'LIM_MIN_POS_CHANGE',
 'LIM_RECENT',
 'MEAN_DAYS_DIFF_CHANGE_0',
 'MEAN_STATUS_COUNT_0',
 'Mobile',
 'QTY_CHLD',
 'REP_POPULATION',
 'REP_SEX',
 'START_DATE',
 'TOTAL_BAL_NEG_CHNG_MAX_180',
 'TOTAL_BAL_NEG_CHNG_MAX_31',
 'TOTAL_BAL_NEG_CHNG_MAX_7',
 'TOTAL_BAL_NEG_CHNG_MAX_90',
 'TOTAL_BAL_NEG_CHNG_MIN_180',
 'TOTAL_BAL_NEG_CHNG_MIN_31',
 'TOTAL_BAL_NEG_CHNG_MIN_7',
 'TOTAL_BAL_NEG_CHNG_MIN_90',
 'TOTAL_BAL_NEG_CHNG_N_180',
 'TOTAL_BAL_NEG_CHNG_N_31',
 'TOTAL_BAL_NEG_CHNG_N_7',
 'TOTAL_BAL_NEG_CHNG_N_90',
 'TOTAL_BAL_NEG_CHNG_SUM_180',
 'TOTAL_BAL_NEG_CHNG_SUM_31',
 'TOTAL_BAL_NEG_CHNG_SUM_7',
 'TOTAL_BAL_NEG_CHNG_SUM_90',
 'TOTAL_BAL_POS_CHNG_MAX_180',
 'TOTAL_BAL_POS_CHNG_MAX_31',
 'TOTAL_BAL_POS_CHNG_MAX_7',
 'TOTAL_BAL_POS_CHNG_MAX_90',
 'TOTAL_BAL_POS_CHNG_MIN_180',
 'TOTAL_BAL_POS_CHNG_MIN_31',
 'TOTAL_BAL_POS_CHNG_MIN_7',
 'TOTAL_BAL_POS_CHNG_MIN_90',
 'TOTAL_BAL_POS_CHNG_N_180',
 'TOTAL_BAL_POS_CHNG_N_31',
 'TOTAL_BAL_POS_CHNG_N_7',
 'TOTAL_BAL_POS_CHNG_N_90',
 'TOTAL_BAL_POS_CHNG_SUM_180',
 'TOTAL_BAL_POS_CHNG_SUM_31',
 'TOTAL_BAL_POS_CHNG_SUM_7',
 'TOTAL_BAL_POS_CHNG_SUM_90',
 'TOTAL_DEBT_NEG_CHNG_MAX_180',
 'TOTAL_DEBT_NEG_CHNG_MIN_180',
 'TOTAL_DEBT_NEG_CHNG_N_180',
 'TOTAL_DEBT_NEG_CHNG_SUM_180',
 'TOTAL_DEBT_POS_CHNG_MAX_180',
 'TOTAL_DEBT_POS_CHNG_MIN_180',
 'TOTAL_DEBT_POS_CHNG_N_180',
 'TOTAL_DEBT_POS_CHNG_SUM_180',
 'TOTAL_MAX_180',
 'TOTAL_MAX_31',
 'TOTAL_MAX_90',
 'TOTAL_MEAN_180',
 'TOTAL_MEAN_31',
 'TOTAL_MEAN_90',
 'TOTAL_N_180',
 'TOTAL_N_31',
 'TOTAL_N_90',
 'TOTAL_SUM_180',
 'TOTAL_SUM_31',
 'TOTAL_SUM_90',
 'TXN_CHN_Internet purchase_MAX_180',
 'TXN_CHN_Internet purchase_MAX_90',
 'TXN_CHN_Internet purchase_MEAN_180',
 'TXN_CHN_Internet purchase_MEAN_90',
 'TXN_CHN_Internet purchase_N_180',
 'TXN_CHN_Internet purchase_N_90',
 'TXN_CHN_Internet purchase_SUM_180',
 'TXN_CHN_Internet purchase_SUM_90',
 'TXN_CHN_Our ATM_MAX_180',
 'TXN_CHN_Our ATM_MEAN_180',
 'TXN_CHN_Our ATM_N_180',
 'TXN_CHN_Our ATM_SUM_180',
 'TXN_CHN_POS terminal_MAX_180',
 'TXN_CHN_POS terminal_MAX_31',
 'TXN_CHN_POS terminal_MAX_90',
 'TXN_CHN_POS terminal_MEAN_180',
 'TXN_CHN_POS terminal_MEAN_31',
 'TXN_CHN_POS terminal_MEAN_90',
 'TXN_CHN_POS terminal_N_180',
 'TXN_CHN_POS terminal_N_31',
 'TXN_CHN_POS terminal_N_90',
 'TXN_CHN_POS terminal_SUM_180',
 'TXN_CHN_POS terminal_SUM_31',
 'TXN_CHN_POS terminal_SUM_90',
 'TXN_CHN_Unknown_MAX_180',
 'TXN_CHN_Unknown_MEAN_180',
 'TXN_CHN_Unknown_N_180',
 'TXN_CHN_Unknown_SUM_180',
 'TXN_TP_ATM_MAX_180',
 'TXN_TP_ATM_MEAN_180',
 'TXN_TP_ATM_N_180',
 'TXN_TP_ATM_SUM_180',
 'TXN_TP_Credit_MAX_180',
 'TXN_TP_Credit_MAX_90',
 'TXN_TP_Credit_MEAN_180',
 'TXN_TP_Credit_MEAN_90',
 'TXN_TP_Credit_N_180',
 'TXN_TP_Credit_N_90',
 'TXN_TP_Credit_SUM_180',
 'TXN_TP_Credit_SUM_90',
 'TXN_TP_MT_MAX_180',
 'TXN_TP_MT_MEAN_180',
 'TXN_TP_MT_N_180',
 'TXN_TP_MT_SUM_180',
 'TXN_TP_POS_MAX_180',
 'TXN_TP_POS_MAX_31',
 'TXN_TP_POS_MAX_90',
 'TXN_TP_POS_MEAN_180',
 'TXN_TP_POS_MEAN_31',
 'TXN_TP_POS_MEAN_90',
 'TXN_TP_POS_N_180',
 'TXN_TP_POS_N_31',
 'TXN_TP_POS_N_90',
 'TXN_TP_POS_SUM_180',
 'TXN_TP_POS_SUM_31',
 'TXN_TP_POS_SUM_90',
 'TXN_TP_Purposeful credit_MAX_180',
 'TXN_TP_Purposeful credit_MEAN_180',
 'TXN_TP_Purposeful credit_N_180',
 'TXN_TP_Purposeful credit_SUM_180']

In [169]:
train['QTY_CHLD']

0         2.0
1         1.0
2         0.0
3         0.0
4         1.0
5         2.0
6         2.0
7         0.0
8         0.0
9         0.0
10        1.0
11        1.0
12        2.0
13        2.0
14        1.0
15        0.0
16        NaN
17        NaN
18        1.0
19        NaN
20        0.0
21        1.0
22        0.0
23        0.0
24        1.0
25        0.0
26        0.0
27        NaN
28        NaN
29        0.0
         ...
114690    NaN
114691    NaN
114692    0.0
114693    2.0
114694    0.0
114695    1.0
114696    3.0
114697    2.0
114698    0.0
114699    0.0
114700    0.0
114701    1.0
114702    1.0
114703    1.0
114704    0.0
114705    1.0
114706    0.0
114707    NaN
114708    1.0
114709    2.0
114710    0.0
114711    NaN
114712    1.0
114713    0.0
114714    0.0
114715    1.0
114716    0.0
114717    1.0
114718    3.0
114719    0.0
Name: QTY_CHLD, Length: 114720, dtype: float64

In [168]:
test['QTY_CHLD']

0              0
1              0
2              1
3              3
4              N
5              0
6              N
7              0
8              1
9              1
10             0
11             2
12             1
13             0
14           NaN
15             2
16       MARRIED
17             0
18             N
19             0
20           NaN
21             1
22           NaN
23             0
24             1
25       MARRIED
26             0
27             1
28             1
29             2
          ...
79514        NaN
79515        NaN
79516        NaN
79517        NaN
79518        NaN
79519        NaN
79520        NaN
79521        NaN
79522        NaN
79523        NaN
79524        NaN
79525        NaN
79526        NaN
79527        NaN
79528        NaN
79529        NaN
79530        NaN
79531        NaN
79532        NaN
79533        NaN
79534        NaN
79535        NaN
79536        NaN
79537        NaN
79538        NaN
79539        NaN
79540        NaN
79541        NaN
79542        NaN
79543        NaN
Name: QTY_CHLD, Length: 79544, dtype: object